# Default values for skao-staging-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: skao-staging-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: staging-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

config:
  baseUserAreaPath: "/tmp/user_areas/"
  allowedMethods:
    - method_1
    - method_2
