FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

ENTRYPOINT ["pytest", "--cov=app", "--cov-report=xml:/app/coverage_output/coverage.xml", "--junitxml=/app/coverage_output/junit.xml", "-o", "junit_family=legacy", "tests"]