name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python (use pre-release Python if 3.13 is unavailable)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.0-beta.1"  # Use pre-release Python version if stable 3.13 is unavailable
          cache: "pip"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run unit tests with coverage
      - name: Run Unit Tests
        run: |
          pytest --cov=app --cov-report=xml tests

      # Step 5: Upload coverage report to Codecov
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
